// <auto-generated />
using GeekShooping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShooping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230610233603_seedDataBase")]
    partial class seedDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShooping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-shirt",
                            Description = "Camiseta Simpsons",
                            ImageUrl = "https://www.stargeek.es/1266-large_default/comprar-camiseta-homer-simpson-biceps-personalizada-ropa-online-de-videojuegos.jpg",
                            Name = "Camiseta Homer Simpsons",
                            Price = 159.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-shirt",
                            Description = "Camiseta Bart Simpsons",
                            ImageUrl = "https://sublistamp.com/11171-large_default/camiseta-de-bart-simpson.jpg",
                            Name = "Camiseta Bart Simpsons",
                            Price = 250.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "COFFE MUG",
                            Description = "Caneca Bart Simpsons",
                            ImageUrl = "https://i.zst.com.br/thumbs/51/e/32/1484288505.jpg",
                            Name = "Caneca Bart",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "COFFE MUG",
                            Description = "Caneca Hommer simpsons",
                            ImageUrl = "https://m.media-amazon.com/images/I/71tZUZ6SmyL._AC_UF894,1000_QL80_.jpg",
                            Name = "Caneca Hommer",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "COFFE MUG",
                            Description = "Caneca Programmer",
                            ImageUrl = "https://i.pinimg.com/originals/0e/a6/63/0ea66335d03125fe176c9dfa1101e719.png",
                            Name = "Caneca Programmer",
                            Price = 159.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "COFFE MUG",
                            Description = "Caneca StarWars",
                            ImageUrl = "https://m.media-amazon.com/images/I/41fnon3MqbL._AC_UF894,1000_QL80_.jpg",
                            Name = "Caneca StarWars",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
